version: '2'
services:
  btn:
    container_name: btn
    image: linuxserver/transmission
    network_mode: container:openvpn
    volumes:
      - ${DOCKER_HOME}/transmission/btn/config:/config
      - ${DOCKER_HOME}/transmission/btn/downloads:/downloads
      - ${DOCKER_HOME}/transmission/btn/watch:/watch
      - /Volumes/Drobo:/Volumes/Drobo
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TIMEZONE}
