version: '2'
services:
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    network_mode: service:openvpn
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_HOME}/jackett/config:/config
      - ${DOCKER_HOME}/jackett/downloads:/downloads
      - ${DOCKER_HOME}/plex/media/TV Shows:/tv
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TIMEZONE}
    depends_on:
      - openvpn

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    network_mode: service:openvpn
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_HOME}/sonarr:/config
      - ${DOCKER_HOME}/deluge/tpb/downloads:/downloads
      - ${DOCKER_HOME}/plex/media/TV Shows:/tv
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TIMEZONE}
    depends_on:
      - openvpn

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    network_mode: service:openvpn
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_HOME}/radarr:/config
      - ${DOCKER_HOME}/deluge/tpb/downloads:/downloads
      - ${DOCKER_HOME}/plex/media/Movies:/movies
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TIMEZONE}
    depends_on:
      - openvpn
