version: '2'
services:
  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb
    volumes:
      - ${DOCKER_HOME}/mariadb:/config
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TIMEZONE}
