version: '2'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - ${DOCKER_HOME}/grafana/data:/var/lib/grafana
      - ${DOCKER_HOME}/grafana/config:/etc/grafana

  influxdb:
    container_name: influxdb
    image: influxdb
    volumes:
      - ${DOCKER_HOME}/influxdb:/var/lib/influxdb
    ports:
      - 25826:25826/udp
      - 8086:8086

  chronograf:
    container_name: chronograf
    image: chronograf
    volumes:
      - ${DOCKER_HOME}/chronograf:/var/lib/chronograf

  kapacitor:
    container_name: kapacitor
    image: kapacitor
    volumes:
      - ${DOCKER_HOME}/kapacitor/data:/var/lib/kapacitor
      - ${DOCKER_HOME}/kapacitor/config/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
