version: '2'
services:
  nextcloud:
    container_name: nextcloud
    image: linuxserver/nextcloud
    networks:
      - link
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TIMEZONE}
    volumes:
      - ${DOCKER_HOME}/nextcloud/data:/data
      - ${DOCKER_HOME}/nextcloud/config:/config/www/nextcloud
networks:
  link:
