version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=${TIMEZONE}
      - ADVERTISE_IP=http://${PLEX_LOCAL_IP}:32400,https://${PLEX_BASE_URL}:443
    volumes:
      - ${DOCKER_HOME}/plex/config:/config
      - ${DOCKER_HOME}/plex/media:/data

  plexpy:
    container_name: plexpy
    image: linuxserver/plexpy
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TIMEZONE}
    volumes:
      - ${DOCKER_HOME}/plexpy:/config
      - ${DOCKER_HOME}/plex/config/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro

  ombi:
    container_name: ombi
    image: linuxserver/ombi
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_HOME}/ombi:/config
