version: '2'
services:
  plexpy:
    container_name: plexpy
    image: linuxserver/plexpy
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TIMEZONE}
    networks:
      - link
    volumes:
      - ${DOCKER_HOME}/plexpy:/config
      - ${DOCKER_HOME}/plex/config/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
networks:
  link:
