version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    privileged: true
    hostname: squirtle
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=${TIMEZONE}
      - ADVERTISE_IP=http://192.168.1.151:32400/
    networks:
      - link
    volumes:
      - ${DOCKER_HOME}/plex/config:/config
      - ${DOCKER_HOME}/plex/media:/data
networks:
  link:
