version: '2'
services:
  proxy:
    container_name: proxy
    image: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${DOCKER_HOME}/proxy/sites-enabled:/etc/nginx/sites-enabled
      - ${DOCKER_HOME}/proxy/content:/var/www/html
      - ${NAS}:${NAS}:ro
    depends_on:
      - openvpn
      - duplicati
      - ghost
      - homeassistant
      - grafana
      - chronograf
      - nextcloud
      - photoshow
      - plex
