version: '2'
services:
  proxy:
    container_name: proxy
    image: proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - link
    volumes:
      - ${DOCKER_HOME}/proxy/sites-enabled:/etc/nginx/sites-enabled
      - ${DOCKER_HOME}/proxy/content:/var/www/html
      - ${NAS}:${NAS}:ro
networks:
  link:
