version: '2'
services:
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    network_mode: container:openvpn
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_HOME}/sonarr:/config
      - ${DOCKER_HOME}/transmission/tpb/downloads:/downloads
      - ${DOCKER_HOME}/plex/media/TV Shows:/tv
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TIMEZONE}
